apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: my-subscritpion
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: my-first-channel
  subscriber: 
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: my-first-app
